# Generated by Django 5.2.4 on 2025-09-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_editora_livro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='ano_publicacao',
            new_name='ano',
        ),
        migrations.AddField(
            model_name='livro',
            name='descricao',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
